package:
    name: volumina_viewer
    version: 0.1

source:
    path: ..

requirements:
    build:
        - python 2.7*
    run:
        - python 2.7*
        - numpy
        - ilastik-meta
        - vigra
        - pyqt 4.11.4 
